### ISSUE TITLE
Using Spring Transaction Management

### ISSUE THREAD

**Issue by tuerepinto** [viniciusxyz/micronaut-transaction-failed#1]
Para usar o trasaction management no micronaut. Troque as duas dependência na pom.xml para 

`<dependency>
    <groupId>io.micronaut</groupId>
    <artifactId>micronaut-spring</artifactId>
</dependency>`

&

`<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-jdbc</artifactId>
    <scope>runtime</scope>
</dependency>`

Link para mais detalhes [micronaut](https://micronaut-projects.github.io/micronaut-sql/latest/guide/)

**Comment by viniciusxyz** [comment]
> Para usar o trasaction management no micronaut. Troque as duas dependência na pom.xml para
> 
> `<dependency> <groupId>io.micronaut</groupId> <artifactId>micronaut-spring</artifactId> </dependency>`
> 
> &
> 
> `<dependency> <groupId>org.springframework</groupId> <artifactId>spring-jdbc</artifactId> <scope>runtime</scope> </dependency>`
> 
> Link para mais detalhes [micronaut](https://micronaut-projects.github.io/micronaut-sql/latest/guide/)

Esse foi um projeto aberto para validar o uso de transações a branch principal tem um exemplo seguindo a doc do micronaut-data e por isso não funciona e mesmo essa forma que você mencionou não funciona corretamente, o que deve ser feito é a configuração que está presente na [branch h2-work desse projeto](https://github.com/viniciusxyz/micronaut-transaction-failed/tree/h2-work), fiz [esse PR](https://github.com/micronaut-projects/micronaut-sql/commit/143d8473b5c7da63625f70b47c7bfb2dad96d2cf) para o micronaut-sql corrigindo essa doc que inclusive já foi mergeado e ficará disponível na página da doc na próxima versão.


Para o funcionamento correto devemos seguir esses passos:

1 - Adicionar as dependências abaixo:

```xml
        <!--Database-->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-jdbc</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.sql</groupId>
            <artifactId>micronaut-jdbc-hikari</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.micronaut.spring</groupId>
            <artifactId>micronaut-spring</artifactId>
            <scope>compile</scope>
        </dependency>
```

2 - Adicionar configurações ao annotation processor:

```xml
         <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                  <annotationProcessorPaths combine.children="append">
                        <path>
                            <groupId>io.micronaut.spring</groupId>
                            <artifactId>micronaut-spring-annotation</artifactId>
                            <version>${micronaut.spring.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-Amicronaut.processing.group=my.transaction.app</arg>
                        <arg>-Amicronaut.processing.module=my-transaction-app</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
```

3 - A partir disso você poderá usar o JDBCTemplate usando anotações @Transactional do Spring quando necessário pois a anotação @Transacional do micronaut-spring-tx foi depreciado e removida no micronaut 3
